sudo: required
language: go
go:
- '1.10'
services:
- docker
env:
  global:
    secure: f1lofDZd+7PHPcV011Bq4nMS2YUcWC231bVSFIVdAcgj9K92kyGLjeyWneJmHHofpM+09R49w8WYeA7M+8xd9E8/qoSeLmYM8FZrSRRn12nz75fvfHsN+M2G4RZeC2DcYH9uUjARUj4o/+PiUHfTF+mG1Zcad3uJBAPzXrSZbwl9b5rkB4uF/8+iKTVTzMvGqwapYJonRDaWpp7jQYYSl7Tl5duE2iYFr3qa1EfBc1IBjOxTHr05I3PhtOu1c16REL08kKZrJIcpmiETinA2ETq1rQJaxnVqLM+5td9nVJ5uBkwBlTli21+MDjVH5Y5ZSofwVe/dHayFce5sgSHLXJxLBIt/fBODCXELIPG0AyUmQfDpZAAWMm9tKkbwxfJrQrfcYhoZWBi866Q0cEXYVDTD0xJpZlRDGRLYlMTLWjumq8BQXh9o0GnwGX/f5siJAQ1K4wtDledWvFGKOQkLfVfgArynbl5S91xn179VZ/OcFMOIpzPCxNehZ2IfhS16H+a+WGOiRtflil+2YbH/1qUM/ZHxeIWVWh5uBJvZ5QxutzTEG24G2JRQF9Ph1uN4a9djRTmT+PwaF6R9uvxz9PR2jsAW1Yn5c88/cz7DvtTjOHu7VDAaw8CBM/Wl81F6AmP/NqOdI2IWyfXrbTQdnWjkqpGzZtEP8quVpt9DFys=
